# Generated by Django 4.0 on 2022-04-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
