# Generated by Django 4.0.3 on 2022-04-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile_picture',
            new_name='profilePicture',
        ),
    ]
