# Generated by Django 4.0.3 on 2022-04-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_customer_id_cart_customer_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profilePicture',
            field=models.ImageField(blank=True, default='images/profiles/user-default.png', help_text='format: required, default-default.png', null=True, upload_to='images/profiles/', verbose_name='user image'),
        ),
    ]
