# Generated by Django 4.0.3 on 2022-04-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_img_url_media_image'),
        ('users', '0006_cart_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='users.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products.productmeta')),
            ],
        ),
    ]
