# Generated by Django 4.0.3 on 2022-04-07 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='img_url',
            new_name='image',
        ),
    ]
